[build]
  base = "client"           # if your React app is in the "client" folder
  publish = "build"         # publish directory is client/build
  functions = "../netlify/functions"  # path from the base directory to your functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

