[build]
  base = "client"
  publish = "build"
  functions = "../netlify/functions"
  command = "npm install && npm run build"

# Redirect for /api/students and any sub-path (covers trailing slash issues)
[[redirects]]
  from = "/api/students/*"
  to = "/.netlify/functions/items/:splat"
  status = 200
  force = true

# Optionally, if you want to also explicitly match /api/students without a trailing slash:
[[redirects]]
  from = "/api/students"
  to = "/.netlify/functions/items"
  status = 200
  force = true

# Wildcard rule for all other API endpoints
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Catch-all rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200