[build]
  base = "client"           # Assuming your client code is in the client folder.
  publish = "build"         # This means the build folder is at client/build.
  functions = "../netlify/functions"  # Adjust this relative path if needed.

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


