[build]
  base = "client"           # if your React app is in the client folder
  publish = "build"         # build output is in client/build
  functions = "../netlify/functions"  # relative path from client/ to your functions folder

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

